# build stage
FROM node:20 AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build -- --output-path=dist

# runtime stage
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
# Opcional: si quieres tu propio nginx.conf, cópialo aquí
# COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
