name: Build and Push Docker image to GHCR and Trigger Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner | toLower }}/pequegest-frontend:latest

      - name: Trigger deploy workflow in PequeGest-Deploy
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DEPLOY_REPO_TOKEN }}
          repository: VolumiDev/PequeGest-Deploy
          event-type: deploy-request
